### ISSUE TITLE
Swift 4.2 update

### ISSUE THREAD

**Issue by NikKovIos** [nspavlo/MaterialActivityIndicator#6]
`CAMediaTimingFunction(name: .easeInEaseOut)` change to `CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseInEaseOut)`

**Comment by nspavlo** [comment]
Can You provide a bit more context?
In version 4.2 `'kCAMediaTimingFunctionEaseInEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeInEaseOut'`.

**Comment by nilsi** [comment]
Was this ever fixed? 

I'm also seeing the same issue on some lines for example:
`animation.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)`

With error:
`Type 'String' has no member 'easeInEaseOut'`

Am I using the wrong version of Swift or something like that? I tried both on 4 and 4.2

**Comment by nspavlo** [comment]
Can You provide a bit more context?
In version 4.2 'kCAMediaTimingFunctionEaseInEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeInEaseOut'
Please verify 'Project -> Build Settings -> Swift Language Version'

**Comment by nilsi** [comment]
Yes, my build settings are set to Swift 4.2. I had the same issue with Swift 4 but tried to upgrade to see if this problem disappeared.

**Comment by nspavlo** [comment]
In order to compile with older versions of swift try `pod 'MaterialActivityIndicator', '~> 0.0.3'`

**Comment by nilsi** [comment]
Thanks for the help,

I actually got it working now. I had to click on Pods in XCode then select MaterialActivityIndicator in the dropdown. Then I changed to Swift 4.2 under the library page and it works now. I can still keep my project in Swift 4 too.

I'm new to iOS development so this might have been obvious for other people.

**Comment by nspavlo** [comment]
:)
