### ISSUE TITLE
Not showing on my view.

### ISSUE THREAD

**Issue by marcelfagadariu** [nspavlo/MaterialActivityIndicator#8]
any idea why it isn't visible on top of my tableview? 

I'm having a uitaleview with constraints on superview and spinner is not visible

**Comment by nspavlo** [comment]
Hey, In order to test `MaterialActivityIndicator` implementation you can try to replace `MaterialActivityIndicator()` with `UIActivityIndicatorView()`

**Comment by marcelfagadariu** [comment]
very awkward.  Tried to add tableView.addSubview(spinnerView) and also not working... also with self.view.... Tried to make that instance of UIActivityIndicator but still not shown... really awkward
